# Generated by Django 5.1.3 on 2025-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='templates1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='templates1/')),
            ],
        ),
        migrations.DeleteModel(
            name='templates',
        ),
    ]
