# Generated by Django 5.1.3 on 2025-01-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_create_alter_templates1_templates1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='templates1',
        ),
    ]
